# Generated by Django 3.0.2 on 2020-02-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_de_custo', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='centrodecusto_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='centrodecusto_usuario',
            field=models.ManyToManyField(to='centro_de_custo.CentroDeCusto'),
        ),
    ]
