# Generated by Django 3.0.2 on 2020-01-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NaturezaOrcamentaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_natureza', models.CharField(max_length=70)),
                ('nome_natureza', models.CharField(max_length=70)),
                ('natureza_orcamento', models.CharField(max_length=140)),
            ],
        ),
    ]
