# Generated by Django 3.0.2 on 2020-01-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('natureza_orcamentaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDeCusto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_centro', models.CharField(max_length=70)),
                ('nome_centro', models.CharField(max_length=70)),
                ('centrodecusto', models.CharField(max_length=70)),
                ('vinculo_natureza', models.ManyToManyField(to='natureza_orcamentaria.NaturezaOrcamentaria')),
            ],
        ),
    ]
