# Generated by Django 3.0.2 on 2020-02-05 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('natureza_orcamentaria', '0001_initial'),
        ('centro_de_custo', '0002_auto_20200203_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroOrcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro_orcamento', models.DateTimeField()),
                ('cc_cadastro_orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='centro_de_custo.CentroDeCusto')),
                ('no_cadastro_orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='natureza_orcamentaria.NaturezaOrcamentaria')),
            ],
        ),
    ]
