# Generated by Django 3.0.2 on 2020-02-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_orcamento', '0002_cadastroorcamento_valor_cadastro_orcamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroorcamento',
            name='data_cadastro_orcamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
