# Generated by Django 3.0.2 on 2020-02-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_orcamento', '0003_auto_20200205_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroorcamento',
            name='obs_cadastro_orcamento',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
